:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2017.1
:: Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
:: 
:: ==============================================================


@echo off

C:/Xilinx2017.1/Vivado_HLS/2017.1/../../Vivado/2017.1/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z010clg400-1 ../xilinx_com_hls_Blowfish_encipher_1_0.zip
