# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_Blowfish_decipher_0_1/design_1_Blowfish_decipher_0_1.xci
# IP: The module: 'design_1_Blowfish_decipher_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_Blowfish_decipher_0_1/constraints/Blowfish_decipher_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Blowfish_decipher_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_Blowfish_decipher_0_1/design_1_Blowfish_decipher_0_1.xci
# IP: The module: 'design_1_Blowfish_decipher_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_Blowfish_decipher_0_1/constraints/Blowfish_decipher_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Blowfish_decipher_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
