# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/design_1_PmodKYPD_1_0.xci
# IP: The module: 'design_1_PmodKYPD_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_pmod_bridge_0_0/PmodKYPD_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_pmod_bridge_0_0 || ORIG_REF_NAME==PmodKYPD_pmod_bridge_0_0}]

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_axi_gpio_0_0/PmodKYPD_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_axi_gpio_0_0 || ORIG_REF_NAME==PmodKYPD_axi_gpio_0_0}]

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_xlslice_0_0/PmodKYPD_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_xlslice_0_0 || ORIG_REF_NAME==PmodKYPD_xlslice_0_0}]

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_xlslice_0_1/PmodKYPD_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_xlslice_0_1 || ORIG_REF_NAME==PmodKYPD_xlslice_0_1}]

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_xlslice_0_2/PmodKYPD_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_xlslice_0_2 || ORIG_REF_NAME==PmodKYPD_xlslice_0_2}]

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_xlslice_t_0_0/PmodKYPD_xlslice_t_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_xlslice_t_0_0 || ORIG_REF_NAME==PmodKYPD_xlslice_t_0_0}]

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_xlconcat_0_0/PmodKYPD_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_xlconcat_0_0 || ORIG_REF_NAME==PmodKYPD_xlconcat_0_0}]

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_pmod_bridge_0_0/PmodKYPD_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodKYPD_pmod_bridge_0_0 || ORIG_REF_NAME==PmodKYPD_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/design_1_PmodKYPD_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodKYPD_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodKYPD_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_axi_gpio_0_0/PmodKYPD_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodKYPD_axi_gpio_0_0 || ORIG_REF_NAME==PmodKYPD_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_axi_gpio_0_0/PmodKYPD_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_axi_gpio_0_0/PmodKYPD_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodKYPD_axi_gpio_0_0 || ORIG_REF_NAME==PmodKYPD_axi_gpio_0_0}] {/U0 }]/U0 ]]

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/design_1_PmodKYPD_1_0.xci
# IP: The module: 'design_1_PmodKYPD_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_pmod_bridge_0_0/PmodKYPD_pmod_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_pmod_bridge_0_0 || ORIG_REF_NAME==PmodKYPD_pmod_bridge_0_0}]

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_axi_gpio_0_0/PmodKYPD_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_axi_gpio_0_0 || ORIG_REF_NAME==PmodKYPD_axi_gpio_0_0}]

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_xlslice_0_0/PmodKYPD_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_xlslice_0_0 || ORIG_REF_NAME==PmodKYPD_xlslice_0_0}]

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_xlslice_0_1/PmodKYPD_xlslice_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_xlslice_0_1 || ORIG_REF_NAME==PmodKYPD_xlslice_0_1}]

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_xlslice_0_2/PmodKYPD_xlslice_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_xlslice_0_2 || ORIG_REF_NAME==PmodKYPD_xlslice_0_2}]

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_xlslice_t_0_0/PmodKYPD_xlslice_t_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_xlslice_t_0_0 || ORIG_REF_NAME==PmodKYPD_xlslice_t_0_0}]

# IP: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_xlconcat_0_0/PmodKYPD_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodKYPD_xlconcat_0_0 || ORIG_REF_NAME==PmodKYPD_xlconcat_0_0}]

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_pmod_bridge_0_0/PmodKYPD_pmod_bridge_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodKYPD_pmod_bridge_0_0 || ORIG_REF_NAME==PmodKYPD_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/design_1_PmodKYPD_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodKYPD_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodKYPD_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_axi_gpio_0_0/PmodKYPD_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodKYPD_axi_gpio_0_0 || ORIG_REF_NAME==PmodKYPD_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_axi_gpio_0_0/PmodKYPD_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/bwedemir/Downloads/ECE4261_Project-Keypad/ECE4261_Project-Keypad/Project_V0.2.srcs/sources_1/bd/design_1/ip/design_1_PmodKYPD_1_0/src/PmodKYPD_axi_gpio_0_0/PmodKYPD_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodKYPD_axi_gpio_0_0 || ORIG_REF_NAME==PmodKYPD_axi_gpio_0_0}] {/U0 }]/U0 ]]
