# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/blowfish_decipher/solution1/impl/vhdl/project.cache/wt [current_project]
set_property parent.project_path C:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/blowfish_decipher/solution1/impl/vhdl/project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/blowfish_decipher/solution1/impl/vhdl/Blowfish_decipher.vhd
  C:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/blowfish_decipher/solution1/impl/vhdl/Blowfish_decipher_AXILiteS_s_axi.vhd
  C:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/blowfish_decipher/solution1/impl/vhdl/Blowfish_decipher_P.vhd
  C:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/blowfish_decipher/solution1/impl/vhdl/Blowfish_decipherbkb.vhd
  C:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/blowfish_decipher/solution1/impl/vhdl/Blowfish_deciphercud.vhd
  C:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/blowfish_decipher/solution1/impl/vhdl/Blowfish_decipherdEe.vhd
  C:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/blowfish_decipher/solution1/impl/vhdl/Blowfish_deciphereOg.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/blowfish_decipher/solution1/impl/vhdl/Blowfish_decipher.xdc
set_property used_in_implementation false [get_files C:/Users/kohara/Downloads/ECE4261_Project-UDP/ECE4261_Project-UDP/blowfish_decipher/solution1/impl/vhdl/Blowfish_decipher.xdc]


synth_design -top Blowfish_decipher -part xc7z010clg400-1 -no_iobuf -mode out_of_context


write_checkpoint -force -noxdef Blowfish_decipher.dcp

catch { report_utilization -file Blowfish_decipher_utilization_synth.rpt -pb Blowfish_decipher_utilization_synth.pb }
