// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xblowfish_decipher.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBlowfish_decipher_CfgInitialize(XBlowfish_decipher *InstancePtr, XBlowfish_decipher_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBlowfish_decipher_Start(XBlowfish_decipher *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_AP_CTRL) & 0x80;
    XBlowfish_decipher_WriteReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XBlowfish_decipher_IsDone(XBlowfish_decipher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XBlowfish_decipher_IsIdle(XBlowfish_decipher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XBlowfish_decipher_IsReady(XBlowfish_decipher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XBlowfish_decipher_EnableAutoRestart(XBlowfish_decipher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBlowfish_decipher_WriteReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XBlowfish_decipher_DisableAutoRestart(XBlowfish_decipher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBlowfish_decipher_WriteReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_AP_CTRL, 0);
}

void XBlowfish_decipher_Set_xl_i(XBlowfish_decipher *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBlowfish_decipher_WriteReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_XL_I_DATA, Data);
}

u32 XBlowfish_decipher_Get_xl_i(XBlowfish_decipher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_XL_I_DATA);
    return Data;
}

u32 XBlowfish_decipher_Get_xl_o(XBlowfish_decipher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_XL_O_DATA);
    return Data;
}

u32 XBlowfish_decipher_Get_xl_o_vld(XBlowfish_decipher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_XL_O_CTRL);
    return Data & 0x1;
}

void XBlowfish_decipher_Set_xr_i(XBlowfish_decipher *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBlowfish_decipher_WriteReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_XR_I_DATA, Data);
}

u32 XBlowfish_decipher_Get_xr_i(XBlowfish_decipher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_XR_I_DATA);
    return Data;
}

u32 XBlowfish_decipher_Get_xr_o(XBlowfish_decipher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_XR_O_DATA);
    return Data;
}

u32 XBlowfish_decipher_Get_xr_o_vld(XBlowfish_decipher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_XR_O_CTRL);
    return Data & 0x1;
}

void XBlowfish_decipher_InterruptGlobalEnable(XBlowfish_decipher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBlowfish_decipher_WriteReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_GIE, 1);
}

void XBlowfish_decipher_InterruptGlobalDisable(XBlowfish_decipher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBlowfish_decipher_WriteReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_GIE, 0);
}

void XBlowfish_decipher_InterruptEnable(XBlowfish_decipher *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_IER);
    XBlowfish_decipher_WriteReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_IER, Register | Mask);
}

void XBlowfish_decipher_InterruptDisable(XBlowfish_decipher *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_IER);
    XBlowfish_decipher_WriteReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_IER, Register & (~Mask));
}

void XBlowfish_decipher_InterruptClear(XBlowfish_decipher *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBlowfish_decipher_WriteReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_ISR, Mask);
}

u32 XBlowfish_decipher_InterruptGetEnabled(XBlowfish_decipher *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_IER);
}

u32 XBlowfish_decipher_InterruptGetStatus(XBlowfish_decipher *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBlowfish_decipher_ReadReg(InstancePtr->Axilites_BaseAddress, XBLOWFISH_DECIPHER_AXILITES_ADDR_ISR);
}

