// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xblowfish_decipher.h"

extern XBlowfish_decipher_Config XBlowfish_decipher_ConfigTable[];

XBlowfish_decipher_Config *XBlowfish_decipher_LookupConfig(u16 DeviceId) {
	XBlowfish_decipher_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XBLOWFISH_DECIPHER_NUM_INSTANCES; Index++) {
		if (XBlowfish_decipher_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XBlowfish_decipher_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XBlowfish_decipher_Initialize(XBlowfish_decipher *InstancePtr, u16 DeviceId) {
	XBlowfish_decipher_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XBlowfish_decipher_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XBlowfish_decipher_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

