-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.1
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Blowfish_encipher is
generic (
    C_S_AXI_AXILITES_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_AXILITES_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_AXILiteS_AWVALID : IN STD_LOGIC;
    s_axi_AXILiteS_AWREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_WVALID : IN STD_LOGIC;
    s_axi_AXILiteS_WREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH/8-1 downto 0);
    s_axi_AXILiteS_ARVALID : IN STD_LOGIC;
    s_axi_AXILiteS_ARREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_RVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_RREADY : IN STD_LOGIC;
    s_axi_AXILiteS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_AXILiteS_BVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_BREADY : IN STD_LOGIC;
    s_axi_AXILiteS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of Blowfish_encipher is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Blowfish_encipher,hls_ip_2017_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.436500,HLS_SYN_LAT=131,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=752,HLS_SYN_LUT=675}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_4770F01 : STD_LOGIC_VECTOR (31 downto 0) := "00000100011101110000111100000001";
    constant ap_const_lv32_74747276 : STD_LOGIC_VECTOR (31 downto 0) := "01110100011101000111001001110110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal xl_i : STD_LOGIC_VECTOR (31 downto 0);
    signal xl_0_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal xl_0_vld_reg : STD_LOGIC := '0';
    signal xl_0_ack_out : STD_LOGIC;
    signal xl_1_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal xl_1_vld_reg : STD_LOGIC := '0';
    signal xl_1_vld_in : STD_LOGIC;
    signal xl_1_ack_in : STD_LOGIC;
    signal xr_i : STD_LOGIC_VECTOR (31 downto 0);
    signal xr_0_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal xr_0_vld_reg : STD_LOGIC := '0';
    signal xr_0_ack_out : STD_LOGIC;
    signal xr_1_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal xr_1_vld_reg : STD_LOGIC := '0';
    signal xr_1_vld_in : STD_LOGIC;
    signal xr_1_ack_in : STD_LOGIC;
    signal P_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal P_ce0 : STD_LOGIC;
    signal P_q0 : STD_LOGIC_VECTOR (30 downto 0);
    signal S_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal S_0_ce0 : STD_LOGIC;
    signal S_0_q0 : STD_LOGIC_VECTOR (30 downto 0);
    signal S_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal S_1_ce0 : STD_LOGIC;
    signal S_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal S_2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal S_2_ce0 : STD_LOGIC;
    signal S_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal S_3_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal S_3_ce0 : STD_LOGIC;
    signal S_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_1_fu_187_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_1_reg_328 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal exitcond_fu_181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Xr_2_fu_198_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Xl_2_fu_205_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal P_load_reg_348 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_1_fu_212_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_reg_353 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_216_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_3_reg_358 : STD_LOGIC_VECTOR (23 downto 0);
    signal Xl_5_fu_231_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Xl_5_reg_363 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal d_fu_242_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal d_reg_368 : STD_LOGIC_VECTOR (7 downto 0);
    signal c_reg_373 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_reg_378 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_reg_383 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal S_0_load_reg_398 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal S_1_load_reg_403 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_fu_296_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_reg_418 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal S_2_load_reg_423 : STD_LOGIC_VECTOR (31 downto 0);
    signal S_3_load_reg_428 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_2_fu_305_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_2_reg_433 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal Xr_5_fu_310_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal Xl_1_reg_150 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_reg_160 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_reg_170 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_193_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_i_fu_277_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_i_fu_281_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_i_fu_285_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_i_fu_289_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal P_load_cast_fu_220_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_227_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_2_fu_223_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal Xl_5_cast_fu_237_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal S_0_load_cast_fu_293_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_1_fu_301_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_block_state11 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);

    component Blowfish_encipher_P IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component Blowfish_encipherbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component Blowfish_enciphercud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Blowfish_encipherdEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Blowfish_enciphereOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Blowfish_encipher_AXILiteS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        xl_o : IN STD_LOGIC_VECTOR (31 downto 0);
        xl_o_ap_vld : IN STD_LOGIC;
        xl_i : OUT STD_LOGIC_VECTOR (31 downto 0);
        xr_o : IN STD_LOGIC_VECTOR (31 downto 0);
        xr_o_ap_vld : IN STD_LOGIC;
        xr_i : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    P_U : component Blowfish_encipher_P
    generic map (
        DataWidth => 31,
        AddressRange => 18,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => P_address0,
        ce0 => P_ce0,
        q0 => P_q0);

    S_0_U : component Blowfish_encipherbkb
    generic map (
        DataWidth => 31,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => S_0_address0,
        ce0 => S_0_ce0,
        q0 => S_0_q0);

    S_1_U : component Blowfish_enciphercud
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => S_1_address0,
        ce0 => S_1_ce0,
        q0 => S_1_q0);

    S_2_U : component Blowfish_encipherdEe
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => S_2_address0,
        ce0 => S_2_ce0,
        q0 => S_2_q0);

    S_3_U : component Blowfish_enciphereOg
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => S_3_address0,
        ce0 => S_3_ce0,
        q0 => S_3_q0);

    Blowfish_encipher_AXILiteS_s_axi_U : component Blowfish_encipher_AXILiteS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_AXILITES_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_AXILITES_DATA_WIDTH)
    port map (
        AWVALID => s_axi_AXILiteS_AWVALID,
        AWREADY => s_axi_AXILiteS_AWREADY,
        AWADDR => s_axi_AXILiteS_AWADDR,
        WVALID => s_axi_AXILiteS_WVALID,
        WREADY => s_axi_AXILiteS_WREADY,
        WDATA => s_axi_AXILiteS_WDATA,
        WSTRB => s_axi_AXILiteS_WSTRB,
        ARVALID => s_axi_AXILiteS_ARVALID,
        ARREADY => s_axi_AXILiteS_ARREADY,
        ARADDR => s_axi_AXILiteS_ARADDR,
        RVALID => s_axi_AXILiteS_RVALID,
        RREADY => s_axi_AXILiteS_RREADY,
        RDATA => s_axi_AXILiteS_RDATA,
        RRESP => s_axi_AXILiteS_RRESP,
        BVALID => s_axi_AXILiteS_BVALID,
        BREADY => s_axi_AXILiteS_BREADY,
        BRESP => s_axi_AXILiteS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        xl_o => xl_1_data_reg,
        xl_o_ap_vld => xl_1_vld_reg,
        xl_i => xl_i,
        xr_o => xr_1_data_reg,
        xr_o_ap_vld => xr_1_vld_reg,
        xr_i => xr_i);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    Xl_1_reg_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                Xl_1_reg_150 <= Xl_5_reg_363;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                Xl_1_reg_150 <= xr_0_data_reg;
            end if; 
        end if;
    end process;

    i_reg_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                i_reg_170 <= i_1_reg_328;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                i_reg_170 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    temp_reg_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                temp_reg_160 <= Xr_5_fu_310_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                temp_reg_160 <= xl_0_data_reg;
            end if; 
        end if;
    end process;

    xl_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    xl_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = xl_1_vld_in) and (ap_const_logic_0 = xl_1_vld_reg))) then 
                xl_1_vld_reg <= ap_const_logic_1;
            elsif (((ap_const_logic_0 = xl_1_vld_in) and (ap_const_logic_1 = xl_1_vld_reg) and (ap_const_logic_1 = ap_const_logic_1))) then 
                xl_1_vld_reg <= ap_const_logic_0;
            end if; 
        end if;
    end process;

    xr_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    xr_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = xr_1_vld_in) and (ap_const_logic_0 = xr_1_vld_reg))) then 
                xr_1_vld_reg <= ap_const_logic_1;
            elsif (((ap_const_logic_0 = xr_1_vld_in) and (ap_const_logic_1 = xr_1_vld_reg) and (ap_const_logic_1 = ap_const_logic_1))) then 
                xr_1_vld_reg <= ap_const_logic_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                P_load_reg_348 <= P_q0;
                tmp_1_reg_353 <= tmp_1_fu_212_p1;
                tmp_3_reg_358 <= tmp_3_fu_216_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                S_0_load_reg_398 <= S_0_q0;
                S_1_load_reg_403 <= S_1_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                S_2_load_reg_423 <= S_2_q0;
                S_3_load_reg_428 <= S_3_q0;
                y_reg_418 <= y_fu_296_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                Xl_5_reg_363 <= Xl_5_fu_231_p2;
                b_reg_378 <= Xl_5_fu_231_p2(23 downto 16);
                c_reg_373 <= Xl_5_cast_fu_237_p2(15 downto 8);
                d_reg_368 <= d_fu_242_p2;
                tmp_5_reg_383 <= Xl_5_fu_231_p2(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                i_1_reg_328 <= i_1_fu_187_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_0 = xl_0_vld_reg)) or (not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = xl_0_vld_reg) and (ap_const_logic_1 = xl_0_ack_out)))) then
                xl_0_data_reg <= xl_i;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = xl_1_vld_in) and (ap_const_logic_0 = xl_1_vld_reg)) or (not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = xl_1_vld_in) and (ap_const_logic_1 = xl_1_vld_reg) and (ap_const_logic_1 = ap_const_logic_1)))) then
                xl_1_data_reg <= Xl_2_fu_205_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_0 = xr_0_vld_reg)) or (not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = xr_0_vld_reg) and (ap_const_logic_1 = xr_0_ack_out)))) then
                xr_0_data_reg <= xr_i;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = xr_1_vld_in) and (ap_const_logic_0 = xr_1_vld_reg)) or (not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = xr_1_vld_in) and (ap_const_logic_1 = xr_1_vld_reg) and (ap_const_logic_1 = ap_const_logic_1)))) then
                xr_1_data_reg <= Xr_2_fu_198_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                y_2_reg_433 <= y_2_fu_305_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, xl_1_ack_in, xr_1_ack_in, ap_CS_fsm_state3, exitcond_fu_181_p2, ap_CS_fsm_state11)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond_fu_181_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state11 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state11) and not(((ap_const_logic_0 = xl_1_ack_in) or (ap_const_logic_0 = xr_1_ack_in))))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    P_address0 <= tmp_fu_193_p1(5 - 1 downto 0);

    P_ce0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            P_ce0 <= ap_const_logic_1;
        else 
            P_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    P_load_cast_fu_220_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(P_load_reg_348),32));
    S_0_address0 <= tmp_3_i_fu_277_p1(8 - 1 downto 0);

    S_0_ce0_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            S_0_ce0 <= ap_const_logic_1;
        else 
            S_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    S_0_load_cast_fu_293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(S_0_load_reg_398),32));
    S_1_address0 <= tmp_4_i_fu_281_p1(8 - 1 downto 0);

    S_1_ce0_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            S_1_ce0 <= ap_const_logic_1;
        else 
            S_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    S_2_address0 <= tmp_5_i_fu_285_p1(8 - 1 downto 0);

    S_2_ce0_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            S_2_ce0 <= ap_const_logic_1;
        else 
            S_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    S_3_address0 <= tmp_6_i_fu_289_p1(8 - 1 downto 0);

    S_3_ce0_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            S_3_ce0 <= ap_const_logic_1;
        else 
            S_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xl_2_fu_205_p2 <= (Xl_1_reg_150 xor ap_const_lv32_74747276);
    Xl_5_cast_fu_237_p2 <= (tmp_3_reg_358 xor tmp_4_fu_227_p1);
    Xl_5_fu_231_p2 <= (P_load_cast_fu_220_p1 xor temp_reg_160);
    Xr_2_fu_198_p2 <= (temp_reg_160 xor ap_const_lv32_4770F01);
    Xr_5_fu_310_p2 <= (y_2_reg_433 xor Xl_1_reg_150);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state11_assign_proc : process(xl_1_ack_in, xr_1_ack_in)
    begin
                ap_block_state11 <= ((ap_const_logic_0 = xl_1_ack_in) or (ap_const_logic_0 = xr_1_ack_in));
    end process;


    ap_done_assign_proc : process(xl_1_ack_in, xr_1_ack_in, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and not(((ap_const_logic_0 = xl_1_ack_in) or (ap_const_logic_0 = xr_1_ack_in))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(xl_1_ack_in, xr_1_ack_in, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and not(((ap_const_logic_0 = xl_1_ack_in) or (ap_const_logic_0 = xr_1_ack_in))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    d_fu_242_p2 <= (tmp_1_reg_353 xor tmp_2_fu_223_p1);
    exitcond_fu_181_p2 <= "1" when (i_reg_170 = ap_const_lv5_10) else "0";
    i_1_fu_187_p2 <= std_logic_vector(unsigned(i_reg_170) + unsigned(ap_const_lv5_1));
    tmp_1_fu_212_p1 <= P_q0(8 - 1 downto 0);
    tmp_2_fu_223_p1 <= temp_reg_160(8 - 1 downto 0);
    tmp_3_fu_216_p1 <= P_q0(24 - 1 downto 0);
    tmp_3_i_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_reg_383),32));
    tmp_4_fu_227_p1 <= temp_reg_160(24 - 1 downto 0);
    tmp_4_i_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_reg_378),32));
    tmp_5_i_fu_285_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_reg_373),32));
    tmp_6_i_fu_289_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(d_reg_368),32));
    tmp_fu_193_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_170),32));

    xl_0_ack_out_assign_proc : process(xl_1_ack_in, xr_1_ack_in, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and not(((ap_const_logic_0 = xl_1_ack_in) or (ap_const_logic_0 = xr_1_ack_in))))) then 
            xl_0_ack_out <= ap_const_logic_1;
        else 
            xl_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    xl_1_ack_in_assign_proc : process(xl_1_vld_reg)
    begin
        if (((ap_const_logic_0 = xl_1_vld_reg) or ((ap_const_logic_1 = xl_1_vld_reg) and (ap_const_logic_1 = ap_const_logic_1)))) then 
            xl_1_ack_in <= ap_const_logic_1;
        else 
            xl_1_ack_in <= ap_const_logic_0;
        end if; 
    end process;


    xl_1_vld_in_assign_proc : process(ap_CS_fsm_state3, exitcond_fu_181_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond_fu_181_p2 = ap_const_lv1_1))) then 
            xl_1_vld_in <= ap_const_logic_1;
        else 
            xl_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;


    xr_0_ack_out_assign_proc : process(xl_1_ack_in, xr_1_ack_in, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and not(((ap_const_logic_0 = xl_1_ack_in) or (ap_const_logic_0 = xr_1_ack_in))))) then 
            xr_0_ack_out <= ap_const_logic_1;
        else 
            xr_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    xr_1_ack_in_assign_proc : process(xr_1_vld_reg)
    begin
        if (((ap_const_logic_0 = xr_1_vld_reg) or ((ap_const_logic_1 = xr_1_vld_reg) and (ap_const_logic_1 = ap_const_logic_1)))) then 
            xr_1_ack_in <= ap_const_logic_1;
        else 
            xr_1_ack_in <= ap_const_logic_0;
        end if; 
    end process;


    xr_1_vld_in_assign_proc : process(ap_CS_fsm_state3, exitcond_fu_181_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond_fu_181_p2 = ap_const_lv1_1))) then 
            xr_1_vld_in <= ap_const_logic_1;
        else 
            xr_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    y_1_fu_301_p2 <= (S_2_load_reg_423 xor y_reg_418);
    y_2_fu_305_p2 <= std_logic_vector(unsigned(S_3_load_reg_428) + unsigned(y_1_fu_301_p2));
    y_fu_296_p2 <= std_logic_vector(unsigned(S_0_load_cast_fu_293_p1) + unsigned(S_1_load_reg_403));
end behav;
