// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XBLOWFISH_DECIPHER_H
#define XBLOWFISH_DECIPHER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xblowfish_decipher_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XBlowfish_decipher_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XBlowfish_decipher;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XBlowfish_decipher_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XBlowfish_decipher_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XBlowfish_decipher_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XBlowfish_decipher_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XBlowfish_decipher_Initialize(XBlowfish_decipher *InstancePtr, u16 DeviceId);
XBlowfish_decipher_Config* XBlowfish_decipher_LookupConfig(u16 DeviceId);
int XBlowfish_decipher_CfgInitialize(XBlowfish_decipher *InstancePtr, XBlowfish_decipher_Config *ConfigPtr);
#else
int XBlowfish_decipher_Initialize(XBlowfish_decipher *InstancePtr, const char* InstanceName);
int XBlowfish_decipher_Release(XBlowfish_decipher *InstancePtr);
#endif

void XBlowfish_decipher_Start(XBlowfish_decipher *InstancePtr);
u32 XBlowfish_decipher_IsDone(XBlowfish_decipher *InstancePtr);
u32 XBlowfish_decipher_IsIdle(XBlowfish_decipher *InstancePtr);
u32 XBlowfish_decipher_IsReady(XBlowfish_decipher *InstancePtr);
void XBlowfish_decipher_EnableAutoRestart(XBlowfish_decipher *InstancePtr);
void XBlowfish_decipher_DisableAutoRestart(XBlowfish_decipher *InstancePtr);

void XBlowfish_decipher_Set_xl_i(XBlowfish_decipher *InstancePtr, u32 Data);
u32 XBlowfish_decipher_Get_xl_i(XBlowfish_decipher *InstancePtr);
u32 XBlowfish_decipher_Get_xl_o(XBlowfish_decipher *InstancePtr);
u32 XBlowfish_decipher_Get_xl_o_vld(XBlowfish_decipher *InstancePtr);
void XBlowfish_decipher_Set_xr_i(XBlowfish_decipher *InstancePtr, u32 Data);
u32 XBlowfish_decipher_Get_xr_i(XBlowfish_decipher *InstancePtr);
u32 XBlowfish_decipher_Get_xr_o(XBlowfish_decipher *InstancePtr);
u32 XBlowfish_decipher_Get_xr_o_vld(XBlowfish_decipher *InstancePtr);

void XBlowfish_decipher_InterruptGlobalEnable(XBlowfish_decipher *InstancePtr);
void XBlowfish_decipher_InterruptGlobalDisable(XBlowfish_decipher *InstancePtr);
void XBlowfish_decipher_InterruptEnable(XBlowfish_decipher *InstancePtr, u32 Mask);
void XBlowfish_decipher_InterruptDisable(XBlowfish_decipher *InstancePtr, u32 Mask);
void XBlowfish_decipher_InterruptClear(XBlowfish_decipher *InstancePtr, u32 Mask);
u32 XBlowfish_decipher_InterruptGetEnabled(XBlowfish_decipher *InstancePtr);
u32 XBlowfish_decipher_InterruptGetStatus(XBlowfish_decipher *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
